### ISSUE TITLE
local path example?

### ISSUE THREAD

**Issue by jdalton** [GSI/jekyll_image_encode#5]
I have a file `base.html` in `_layouts/base.html` where I have:
```html
<link rel="icon" type="image/png" href="{% base64 '/icons/favicon-16x16.png' %}" sizes="16x16">
```
When I build though it errors with: 
```shell
Liquid Exception: No such file or directory - '/icons/favicon-16x16.png' in /_layouts/base.html
```

Could you provide a usage example for local use?

**Comment by GSI** [comment]
The JIE tag is intended for use with remote (http) sources.

However, you may find a way to reference local (file) resources if Ruby's OpenUri supports it.

You may want to start out by looking at lib/jekyll_image_encode.rb at around line 34.

**Comment by jdalton** [comment]
Thanks!

I found out that it had to be a path like this (minus the quotes):
> {% base64 icons/favicon-16x16.png %}
